version: "3.8"

services:
  nodejs-app:
    build: .
    ports:
      - "8000:8000"  # Expose the Node.js app
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - CROSS_ORIGIN=${CROSS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  # Prometheus web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Use static Prometheus config
    environment:
      - NODEJS_APP_IP=nodejs-app  # Use the service name as the dynamic IP
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
