global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:8000']  # Use the service name directly as the hostname
    metrics_path: '/api/v1/admin/metrics'
